name:                rpki-prover
version:             0.1.0.0
github:              "lolepezy/rpki-prover"
license:             BSD3
author:              "Mikhail Puzanov"
maintainer:          "misha.puzanov@gmail.com"
copyright:           "2019 Mikhail Puzanov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rpki-prover#readme>

default-extensions: ViewPatterns, LambdaCase, ScopedTypeVariables, 
                    AllowAmbiguousTypes, ConstraintKinds, DataKinds, 
                    DeriveDataTypeable, DeriveGeneric, DeriveFunctor, 
                    DuplicateRecordFields, FlexibleContexts, GADTs, 
                    KindSignatures, MultiWayIf, NoMonomorphismRestriction, 
                    PatternSynonyms, PolyKinds, RankNTypes, StandaloneDeriving, 
                    TupleSections, TypeApplications, TypeFamilies, TypeOperators

dependencies:
- base >= 4.7 && < 5
- asn1-encoding
- asn1-parse
- asn1-types
- async
- base16-bytestring
- base64-bytestring
- bytestring
- bytestring-conversion
- containers
- cryptohash-sha256
- deepseq
- directory
- dlist
- filemanip
- generic-lens
- hashable
- hex
- hourglass
- hw-ip
- interpolate
- ixset-typed
- lens
- MissingH
- mtl
- pem
- primitive
- semigroups
- stm
- stm-containers
- string-conversions
- text
- text-short
- time
- transformers
- validation
- wreq
- x509
- x509-store
- x509-validation
- xeno
- QuickCheck
- tasty
- tasty-hunit
- tasty-quickcheck    
- generic-arbitrary
- quickcheck-instances

library:
  source-dirs: src

executables:
  rpki-prover-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -Wall
    - -with-rtsopts=-N
    dependencies:
    - rpki-prover

tests:
  rpki-prover-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - rpki-prover
    - QuickCheck
    - tasty
    - tasty-hunit
    - tasty-quickcheck    
    - generic-arbitrary
    - quickcheck-instances
